### ISSUE TITLE
Provide a license 

### ISSUE THREAD

**Issue by jdittrich** [mre/pandoc-memoir#1]
**Story:** As a user, I want use and build upon the _pandoc-memoir_ template;  If I write a book using _pandoc_, I would like to provide all needed data with it, also templates. 

**Problem:** _Pandoc-memoir_ currently does not specify any license, which makes including or changing it at [a legally uncertain action](https://choosealicense.com/no-license/) at best.

**Solution:** [Provide a license](https://choosealicense.com/) like [MIT](https://choosealicense.com/licenses/mit/) or [Apache](https://choosealicense.com/licenses/apache-2.0/)

**Comment by mre** [comment]
Oh sure! Added a license. Would be happy if you send a message in case you build anything cool with it. Have fun! ⭐️
