### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by trenkert** [mre/pandoc-memoir#2]
there is little documentation in the template file itself. How can headers be activated, for instance? The template includes an option for fancyhdr, but they don't get rendered.

**Comment by mre** [comment]
Hi @trenkert,
fancyhdr is for rendering headers and footers, right? It's a while ago, but I just had another look and there is a footer in the rendered PDF. [Here](https://github.com/mre/pandoc-memoir/blob/4cf08dcdb5a046675900b7ba480b98804f315752/templates/extended.tex#L255)'s the TeX for that. 
The idea is, that it all runs out of the box and that the header/footer styles are predefined. If you like to adjust that, probably the best way is to fork the project and adjust the template to your needs. There might also be a way to do that with pandoc.

Thanks for your request. I'm open for alternative suggestions and pull requests of course. 😉
